apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: deliverycenter-service-osrm-bicycle
  name: deliverycenter-service-osrm-bicycle
  namespace: production
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: deliverycenter-service-osrm-bicycle
    spec:
      containers:
      - image: gcr.io/deliverycenter-prod/deliverycenter-service-osrm:latest
        name: deliverycenter-service-osrm-bicycle
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /nearest/v1/healthz/0,0
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources: {}
        stdin: true
        tty: true
status: {}
